project_id = "bqxdbvrtohhgkusmdjxd"

# Auth webhook removed to use Supabase's native email system
# Custom emails will be triggered via database functions when needed

[functions.auth-emails]
verify_jwt = false

[functions.test-auth-webhook]
verify_jwt = false

[functions.create-technician-accounts]
verify_jwt = false

[functions.setup-super-admin]
verify_jwt = false