-- Update get_maintenance_history RPC function to include comprehensive chiller fields
CREATE OR REPLACE FUNCTION public.get_maintenance_history(p_company_id uuid DEFAULT NULL::uuid, p_equipment_id uuid DEFAULT NULL::uuid, p_location_id uuid DEFAULT NULL::uuid, p_technician_id uuid DEFAULT NULL::uuid, p_start_date timestamp with time zone DEFAULT NULL::timestamp with time zone, p_end_date timestamp with time zone DEFAULT NULL::timestamp with time zone, p_limit integer DEFAULT 50)
 RETURNS TABLE(
    id uuid, 
    equipment_id uuid, 
    technician_id uuid, 
    company_id uuid, 
    location_id uuid, 
    check_date timestamp with time zone, 
    status maintenance_check_status, 
    equipment_type text, 
    reading_mode text, 
    air_filter_status text, 
    belt_condition text, 
    motor_condition text, 
    control_system_status text, 
    notes text, 
    maintenance_frequency text, 
    vibration_observed boolean, 
    unusual_noise boolean, 
    drainage_system_status text, 
    sump_basin_condition text, 
    strainer_status text, 
    pump_seals_condition text, 
    motor_lubrication_status text, 
    fan_assembly_status text, 
    drift_eliminators_condition text, 
    fill_media_condition text, 
    water_system_status text, 
    general_inspection text, 
    emergency_shutdown_status text, 
    vibration_monitoring text, 
    seasonal_preparation_status text, 
    sensor_status text, 
    toilet_status text, 
    safety_features_status text, 
    elevator_operation text, 
    door_operation text, 
    images text[], 
    maintenance_recommendations text, 
    urinal_status text, 
    corrective_actions text, 
    troubleshooting_notes text, 
    airflow_unit character varying, 
    compressor_condition text, 
    emergency_phone text, 
    elevator_lighting text, 
    elevator_notes text, 
    hand_dryer_status text, 
    cleanliness_level text, 
    soap_supply text, 
    toilet_paper_supply text, 
    floor_condition text, 
    restroom_notes text, 
    refrigerant_level text, 
    inspection_notes text, 
    unusual_noise_description text, 
    electrical_connections_condition text, 
    vibration_description text, 
    drain_pan_status text, 
    sensors_operation text, 
    coils_condition text, 
    dampers_operation text, 
    fan_noise_level text, 
    oil_level_status text, 
    condenser_condition text, 
    chemical_treatment_status text, 
    control_panel_condition text, 
    sink_status text, 
    fan_belt_condition text, 
    evaporator_condition text, 
    safety_switches_status text, 
    air_filter_cleaned boolean, 
    fan_bearings_lubricated boolean, 
    airflow_reading numeric, 
    unusual_noise_elevator boolean, 
    vibration_elevator boolean, 
    city_conductivity_us_cm numeric, 
    tower_conductivity_us_cm numeric,
    -- Comprehensive chiller fields - Evaporator
    evaporator_approach_temp numeric,
    evaporator_leaving_water_temp numeric,
    evaporator_entering_water_temp numeric,
    evaporator_pressure_drop numeric,
    evaporator_flow_rate numeric,
    -- Comprehensive chiller fields - Condenser  
    condenser_approach_temp numeric,
    condenser_entering_water_temp numeric,
    condenser_leaving_water_temp numeric,
    condenser_pressure_drop numeric,
    condenser_flow_rate numeric,
    -- Comprehensive chiller fields - Compressor
    compressor_suction_temp numeric,
    compressor_discharge_temp numeric,
    compressor_suction_pressure numeric,
    compressor_discharge_pressure numeric,
    compressor_superheat numeric,
    compressor_subcooling numeric,
    compressor_oil_pressure numeric,
    compressor_oil_temp numeric,
    -- Comprehensive chiller fields - Motor
    motor_amperage_rla numeric,
    motor_voltage_phase1 numeric,
    motor_voltage_phase2 numeric,
    motor_voltage_phase3 numeric,
    motor_temperature numeric,
    motor_vibration numeric,
    -- Comprehensive chiller fields - Performance
    system_efficiency_rating numeric,
    energy_consumption_kwh numeric,
    operating_hours numeric,
    cooling_capacity_tons numeric,
    heating_capacity_btuh numeric,
    efficiency_cop numeric,
    -- Comprehensive chiller fields - Water quality
    water_ph_level numeric,
    water_conductivity numeric,
    -- Comprehensive chiller fields - Maintenance actions
    filters_replaced boolean,
    coils_cleaned boolean,
    belts_inspected boolean,
    bearings_lubricated boolean,
    refrigerant_checked boolean,
    -- Comprehensive chiller fields - Follow-up
    follow_up_required boolean,
    next_inspection_date timestamp with time zone,
    maintenance_duration_minutes integer,
    labor_cost numeric,
    parts_cost numeric,
    parts_used jsonb,
    ambient_temperature numeric,
    humidity_level numeric,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY
  SELECT 
    hmc.id,
    hmc.equipment_id,
    hmc.technician_id,
    hmc.company_id,
    hmc.location_id,
    hmc.check_date,
    hmc.status,
    hmc.equipment_type,
    hmc.reading_mode,
    hmc.air_filter_status,
    hmc.belt_condition,
    hmc.motor_condition,
    hmc.control_system_status,
    hmc.notes,
    hmc.maintenance_frequency,
    hmc.vibration_observed,
    hmc.unusual_noise,
    hmc.drainage_system_status,
    hmc.sump_basin_condition,
    hmc.strainer_status,
    hmc.pump_seals_condition,
    hmc.motor_lubrication_status,
    hmc.fan_assembly_status,
    hmc.drift_eliminators_condition,
    hmc.fill_media_condition,
    hmc.water_system_status,
    hmc.general_inspection,
    hmc.emergency_shutdown_status,
    hmc.vibration_monitoring,
    hmc.seasonal_preparation_status,
    hmc.sensor_status,
    hmc.toilet_status,
    hmc.safety_features_status,
    hmc.elevator_operation,
    hmc.door_operation,
    hmc.images,
    hmc.maintenance_recommendations,
    hmc.urinal_status,
    hmc.corrective_actions,
    hmc.troubleshooting_notes,
    hmc.airflow_unit,
    hmc.compressor_condition,
    hmc.emergency_phone,
    hmc.elevator_lighting,
    hmc.elevator_notes,
    hmc.hand_dryer_status,
    hmc.cleanliness_level,
    hmc.soap_supply,
    hmc.toilet_paper_supply,
    hmc.floor_condition,
    hmc.restroom_notes,
    hmc.refrigerant_level,
    hmc.inspection_notes,
    hmc.unusual_noise_description,
    hmc.electrical_connections_condition,
    hmc.vibration_description,
    hmc.drain_pan_status,
    hmc.sensors_operation,
    hmc.coils_condition,
    hmc.dampers_operation,
    hmc.fan_noise_level,
    hmc.oil_level_status,
    hmc.condenser_condition,
    hmc.chemical_treatment_status,
    hmc.control_panel_condition,
    hmc.sink_status,
    hmc.fan_belt_condition,
    hmc.evaporator_condition,
    hmc.safety_switches_status,
    hmc.air_filter_cleaned,
    hmc.fan_bearings_lubricated,
    hmc.airflow_reading,
    hmc.unusual_noise_elevator,
    hmc.vibration_elevator,
    hmc.city_conductivity_us_cm,
    hmc.tower_conductivity_us_cm,
    -- Add comprehensive chiller fields to SELECT
    hmc.evaporator_approach_temp,
    hmc.evaporator_leaving_water_temp,
    hmc.evaporator_entering_water_temp,
    hmc.evaporator_pressure_drop,
    hmc.evaporator_flow_rate,
    hmc.condenser_approach_temp,
    hmc.condenser_entering_water_temp,
    hmc.condenser_leaving_water_temp,
    hmc.condenser_pressure_drop,
    hmc.condenser_flow_rate,
    hmc.compressor_suction_temp,
    hmc.compressor_discharge_temp,
    hmc.compressor_suction_pressure,
    hmc.compressor_discharge_pressure,
    hmc.compressor_superheat,
    hmc.compressor_subcooling,
    hmc.compressor_oil_pressure,
    hmc.compressor_oil_temp,
    hmc.motor_amperage_rla,
    hmc.motor_voltage_phase1,
    hmc.motor_voltage_phase2,
    hmc.motor_voltage_phase3,
    hmc.motor_temperature,
    hmc.motor_vibration,
    hmc.system_efficiency_rating,
    hmc.energy_consumption_kwh,
    hmc.operating_hours,
    hmc.cooling_capacity_tons,
    hmc.heating_capacity_btuh,
    hmc.efficiency_cop,
    hmc.water_ph_level,
    hmc.water_conductivity,
    hmc.filters_replaced,
    hmc.coils_cleaned,
    hmc.belts_inspected,
    hmc.bearings_lubricated,
    hmc.refrigerant_checked,
    hmc.follow_up_required,
    hmc.next_inspection_date,
    hmc.maintenance_duration_minutes,
    hmc.labor_cost,
    hmc.parts_cost,
    hmc.parts_used,
    hmc.ambient_temperature,
    hmc.humidity_level,
    hmc.created_at,
    hmc.updated_at
  FROM public.hvac_maintenance_checks hmc
  WHERE 
    (p_company_id IS NULL OR hmc.company_id = p_company_id) AND
    (p_equipment_id IS NULL OR hmc.equipment_id = p_equipment_id) AND
    (p_location_id IS NULL OR hmc.location_id = p_location_id) AND
    (p_technician_id IS NULL OR hmc.technician_id = p_technician_id) AND
    (p_start_date IS NULL OR hmc.check_date >= p_start_date) AND
    (p_end_date IS NULL OR hmc.check_date <= p_end_date) AND
    (
      can_access_all_data() OR 
      (hmc.company_id IS NOT NULL AND is_member_of(hmc.company_id))
    )
  ORDER BY hmc.check_date DESC, hmc.created_at DESC
  LIMIT LEAST(p_limit, 1000);
END;
$function$;