// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqxdbvrtohhgkusmdjxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxeGRidnJ0b2hoZ2t1c21kanhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMTA5MzgsImV4cCI6MjA0OTg4NjkzOH0.DfGbaVvQFJ1kXAVdD-CsTX21vasF9yR-3MDOLn8g5-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'apikey': SUPABASE_PUBLISHABLE_KEY
    }
  }
});

// Create a token-aware client that ensures JWT is always included
export const createAuthenticatedClient = (accessToken: string) => {
  console.log("🔑 Creating authenticated client with token:", accessToken.substring(0, 20) + "...");
  
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Authorization': `Bearer ${accessToken}`,
        // Ensure JWT is in request for RLS
        'X-Supabase-JWT': accessToken
      }
    }
  });
};

// Helper function to get authenticated client with current session
export const getAuthenticatedClient = async () => {
  const { data: { session } } = await supabase.auth.getSession();
  
  if (!session?.access_token) {
    console.warn("❌ No access token available for authenticated client");
    throw new Error("No valid session for authenticated client");
  }
  
  // Validate the session is complete
  if (!session.user?.id) {
    console.warn("❌ Incomplete session data");
    throw new Error("Incomplete session data");
  }
  
  console.log("✅ Creating authenticated client with valid token");
  const client = createAuthenticatedClient(session.access_token);
  
  // Test the client immediately
  try {
    const { data: authTest, error } = await client.rpc('debug_auth_uid');
    if (error) {
      console.error("❌ JWT validation failed:", error);
      throw new Error(`JWT validation failed: ${error.message}`);
    }
    
    if (!authTest?.[0]?.auth_uid) {
      console.error("❌ auth.uid() is null - JWT not transmitted");
      throw new Error("JWT token not properly transmitted to database");
    }
    
    console.log("✅ JWT successfully validated:", authTest[0].auth_uid);
    return client;
  } catch (error) {
    console.error("❌ Auth client validation failed:", error);
    throw error;
  }
};